
package com.shop.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Fri Apr 14 22:55:50 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "Registe", namespace = "http://www.com.shop")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Registe", namespace = "http://www.com.shop", propOrder = {"username", "motDePasse"})

public class Registe {

    @XmlElement(name = "username")
    private int username;
    @XmlElement(name = "motDePasse")
    private int motDePasse;

    public int getUsername() {
        return this.username;
    }

    public void setUsername(int newUsername)  {
        this.username = newUsername;
    }

    public int getMotDePasse() {
        return this.motDePasse;
    }

    public void setMotDePasse(int newMotDePasse)  {
        this.motDePasse = newMotDePasse;
    }

}

