
package shop.com.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T23:01:26.933+02:00
 * Generated source version: 3.5.5
 *
 */
public final class Fonction_FonctionPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.com.shop", "fonctionService");

    private Fonction_FonctionPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FonctionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FonctionService ss = new FonctionService(wsdlURL, SERVICE_NAME);
        Fonction port = ss.getFonctionPort();

        {
        System.out.println("Invoking getPriceofProduct...");
        int _getPriceofProduct_prodId = 1;
        int _getPriceofProduct__return = port.getPriceofProduct(_getPriceofProduct_prodId);
        System.out.println("getPriceofProduct.result=" + _getPriceofProduct__return);


        }
        {
        System.out.println("Invoking removeProductCart...");
        int _removeProductCart_id = 4;
        port.removeProductCart(_removeProductCart_id);


        }
        {
        System.out.println("Invoking order...");
        int _order_id = 1;
        port.order(_order_id);


        }
        {
        System.out.println("Invoking registe...");
        int _registe_username = 111;
        int _registe_motDePasse = 20;
        java.lang.String _registe__return = port.registe(_registe_username, _registe_motDePasse);
        System.out.println("registe.result=" + _registe__return);


        }
        {
        System.out.println("Invoking addProductCart...");
        int _addProductCart_username = 111;
        int _addProductCart_prodId = 1;
        port.addProductCart(_addProductCart_username, _addProductCart_prodId);


        }

        System.exit(0);
    }

}
