package shop.com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T23:01:27.004+02:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://www.com.shop", name = "fonction")
@XmlSeeAlso({ObjectFactory.class})
public interface Fonction {

    @WebMethod
    @RequestWrapper(localName = "getPriceofProduct", targetNamespace = "http://www.com.shop", className = "shop.com.client.GetPriceofProduct")
    @ResponseWrapper(localName = "getPriceofProductResponse", targetNamespace = "http://www.com.shop", className = "shop.com.client.GetPriceofProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getPriceofProduct(

        @WebParam(name = "prodId", targetNamespace = "")
        int prodId
    );

    @WebMethod
    @RequestWrapper(localName = "removeProductCart", targetNamespace = "http://www.com.shop", className = "shop.com.client.RemoveProductCart")
    @ResponseWrapper(localName = "removeProductCartResponse", targetNamespace = "http://www.com.shop", className = "shop.com.client.RemoveProductCartResponse")
    public void removeProductCart(

        @WebParam(name = "id", targetNamespace = "")
        int id
    );

    @WebMethod(operationName = "Order")
    @RequestWrapper(localName = "Order", targetNamespace = "http://www.com.shop", className = "shop.com.client.Order")
    @ResponseWrapper(localName = "OrderResponse", targetNamespace = "http://www.com.shop", className = "shop.com.client.OrderResponse")
    public void order(

        @WebParam(name = "id", targetNamespace = "")
        int id
    );

    @WebMethod(operationName = "Registe")
    @RequestWrapper(localName = "Registe", targetNamespace = "http://www.com.shop", className = "shop.com.client.Registe")
    @ResponseWrapper(localName = "RegisteResponse", targetNamespace = "http://www.com.shop", className = "shop.com.client.RegisteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String registe(

        @WebParam(name = "username", targetNamespace = "")
        int username,
        @WebParam(name = "motDePasse", targetNamespace = "")
        int motDePasse
    );

    @WebMethod
    @RequestWrapper(localName = "addProductCart", targetNamespace = "http://www.com.shop", className = "shop.com.client.AddProductCart")
    @ResponseWrapper(localName = "addProductCartResponse", targetNamespace = "http://www.com.shop", className = "shop.com.client.AddProductCartResponse")
    public void addProductCart(

        @WebParam(name = "username", targetNamespace = "")
        int username,
        @WebParam(name = "prodId", targetNamespace = "")
        int prodId
    );
}
